/**
 * Standardized error codes for API responses.
 * Frontend can match on these for i18n and UX decisions.
 */
export const ERROR_CODES = {
    // Auth
    AUTH_REQUIRED: "AUTH_REQUIRED",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
    AUTH_INVALID_OTP: "AUTH_INVALID_OTP",
    AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
    AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

    // Validation
    VALIDATION_ERROR: "VALIDATION_ERROR",
    MISSING_FIELD: "MISSING_FIELD",
    INVALID_FORMAT: "INVALID_FORMAT",

    // Resources
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    ALREADY_EXISTS: "ALREADY_EXISTS",

    // Booking
    ROOM_UNAVAILABLE: "ROOM_UNAVAILABLE",
    BOOKING_EXPIRED: "BOOKING_EXPIRED",
    BOOKING_ALREADY_CANCELLED: "BOOKING_ALREADY_CANCELLED",
    BOOKING_NOT_CANCELLABLE: "BOOKING_NOT_CANCELLABLE",

    // Payment
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_SIGNATURE_INVALID: "PAYMENT_SIGNATURE_INVALID",
    INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",

    // KYC
    KYC_ALREADY_SUBMITTED: "KYC_ALREADY_SUBMITTED",
    KYC_DOCUMENT_INVALID: "KYC_DOCUMENT_INVALID",

    // Rate Limiting
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

    // Server
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
